apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView
from util import RequestStaff
import views

urlpatterns = patterns('',
    url(r'^signup/$', views.RegisterUser, name='signup'),
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm),
    url(r'^signin/$', login, name='login', kwargs={"template_name": "users/login.html"}),
    url(r'^logout_confirm/$', TemplateView.as_view(template_name='users/logout.html'), name="logout_confirm"),
    url(r'^logout/$', logout, name='logout'),

    url(r'^ListUsers$', RequestStaff()(views.ListUsers.as_view()), name='ListUsers'),
    url(r'^UpdateUser/(?P<pk>[0-9]+)/$', RequestStaff()(views.UpdateUser.as_view()), name='UpdateUser'),
    url(r'^DeleteUser/(?P<pk>[0-9]+)/$', RequestStaff()(views.DeleteUser.as_view()), name='DeleteUser'),

    url(r'^EnableCurrentUserProductManagement/$', views.EnableCurrentUserProductManagement),
)

apps/products/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
#from relish.helpers import upload_to

class Shop(models.Model):
  title = models.CharField(max_length=255)
  url = models.URLField(unique=True, max_length=255)
  feedbackNumber = models.PositiveIntegerField()
  score = models.FloatField(default=0.0)
  lastVisited = models.DateTimeField(auto_now_add=True)
  class Meta: 
    # These models are also used by scrapy. Django automatically adds app label as the table prefix. We need to tell this prefix to scrapy.
    db_table = "products_shop"

class ProductStatus(models.Model):
  status = models.CharField(max_length=255, default='dummy product status', null=False)
  def __unicode__(self):
    return self.status
  class Meta: 
    db_table = "products_productstatus"

# insert default statuses
# when the first time manage.py migrate is called, products_productstatus table is not created yet. get_or_create() will fail
try: 
  ProductStatus.objects.get_or_create(status = '1_not_yet_processed')[0].save()
  ProductStatus.objects.get_or_create(status = '2_ordered_not_arrived')[0].save()
  ProductStatus.objects.get_or_create(status = '3_ordered_arrived')[0].save()
  ProductStatus.objects.get_or_create(status = '4_to_be_ordered')[0].save()
  ProductStatus.objects.get_or_create(status = '5_not_to_order_any_more (low profit)')[0].save()
  ProductStatus.objects.get_or_create(status = '6_not_to_order_any_more (no provider)')[0].save()
  ProductStatus.objects.get_or_create(status = '7_not_to_order_any_more (high purchase price)')[0].save()
except:
  pass

class Product(models.Model):
  """Very simple product"""
  internalId = models.PositiveIntegerField(null=True)
  url = models.URLField(unique=True, max_length=255)
  # this field is outdated. It is created for affiliate system only. Should be moved to Metric.
  retailPrice = models.PositiveIntegerField(_("Retail price"), default=999, null=False)
  title = models.CharField(null=False, max_length=255)
  category = models.CharField(max_length=255, default="dummy category")
  description = models.CharField(max_length=255, default="dummy description")
  imagePath = models.CharField(max_length=255, default='dummy image path')
  similarity = models.FloatField(default=0.0) # the simularity of this products on buka and lazada

  status = models.ForeignKey(ProductStatus, null=True)
  sellingUrls = models.URLField(null=True, max_length=255)
  stock = models.PositiveIntegerField(default=1, null=True)

  # One-To-Many relationship (shop has many products)
  # sometime, shop is not important. So, set null = True
  shop = models.ForeignKey(Shop, related_name='products', null = True)
  #searchKeys = models.ForeignKey(SearchKeys, related_name = 'products' )

  class Meta:
    verbose_name = _('Product')
    verbose_name_plural = _('Products')
    db_table = "products_product"

  def __unicode__(self):
    return "id:%s, internalId:%s, %s" % (self.id, self.internalId, self.title)

  def get_image_url(self):
    if self.image:
      return self.image.url
    else:
      return settings.DEFAULT_IMAGE

class SearchKey(models.Model):
  searchKey = models.CharField(max_length=255)
  subSearchKey = models.CharField(max_length=255)
  product = models.ForeignKey(Product)
  class Meta: 
    db_table = "products_searchkey"

# METRICS TABLE
class Metrics(models.Model):
  '''
  We trace the data of each product at different times. 
  So, each product has multiple metrics
  '''
  timestamp = models.DateTimeField(auto_now_add=True)
  pageviews = models.PositiveIntegerField(default=0, null=True)
  likes = models.PositiveIntegerField(default=0, null=True)
  price = models.PositiveIntegerField(default=0, null=True)
  sales = models.PositiveIntegerField(default=0, null=True)
  commentNumber = models.PositiveIntegerField(default=0, null=True) 
  score = models.FloatField(default=0.0, null=True)
  #stock = models.PositiveIntegerField(default=0)
  # One-To-Many relationship (product has many metrics)
  product = models.ForeignKey(Product, related_name='metrics')

  class Meta: 
    db_table = "products_metrics"

class Keywords(models.Model):
  # https://docs.djangoproject.com/en/1.8/ref/models/fields/
  # .save() always fails once I use primary_key = true. 
  # The reason is unclear.
  keyword = models.CharField(unique=True, max_length=255)
  seedKeyword = models.CharField(max_length=255)
  seedExpander = models.CharField(max_length=255)

  searchVolume = models.PositiveIntegerField()
  averageCpc = models.IntegerField()
  competition = models.FloatField()
  productNumber = models.PositiveIntegerField()

  class Meta: 
    db_table = "products_keywords"

  # https://docs.djangoproject.com/en/1.8/ref/models/fields/
  # .save() always fails once I use primary_key = true. 
  # The reason is unclear.

  def Init(self, _seedKeyword='', _seedExpander='', _keyword='', _searchVolume=-1, _averageCpc=-1, _competition=-1, _productNumber=-1):
    self.seedKeyword = _seedKeyword
    self.seedExpander = _seedExpander
    self.keyword = _keyword
    self.searchVolume = _searchVolume
    self.averageCpc = _averageCpc
    self.competition = _competition
    self.productNumber = _productNumber

from apps.users.models import User
class VisitorStatus(models.Model):
  user = models.ForeignKey(User)
  product = models.ForeignKey(Product)

  time = models.DateTimeField(auto_now_add=True)
  ip = models.GenericIPAddressField()

  isOrder = models.BooleanField(default=False)
  orderMailId = models.CharField(max_length=32, null=True)
  orderMailDate = models.DateTimeField(null=True)

templates/templates/partner/affiliate.html
{% extends "partner/affiliate_common/base.html" %}
{% load i18n %}
{% load affiliate_tags %}

{% block affiliate_content %}
    {% if affiliate %}
        <h3>{% trans "Your code" %}</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>{% trans "Title" %}</td>
                    <td>{% trans "Code" %}</td>
                    <td>{% trans "Example" %}</td>
                </tr>
            </thead>
            <tr>
                <td>{% trans "Affiliate code" %}</td>
                <td>{{affiliate.aid}}</td>
                <td></td>
            </tr>
            <tr>
                <td>{% trans "Affiliate link" %}</td>
                <td>{{affiliate.render_link}}</td>
                <td></td>
            </tr>
            <tr>
                <td>{% trans "Affiliate link for website" %}</td>
                <td>{{affiliate.render_html_a}}</td>
                <td>{{affiliate.render_html_a|safe}}</td>
            </tr>
            {% for banner in banners %}
                <tr>
                    <td>{% trans "Affiliate banner for website" %} ({{banner.image.width}}x{{banner.image.height}})</td>
                    <td>{% render_banner affiliate banner autoescape=True %}</td>
                    <td>{% render_banner affiliate banner %}</td>
                </tr>
            {% endfor %}
        </table>

        <h3>{% trans "Your stats" %}</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>{% trans "Current balance" %}, {{ currency_label }}</td>
                    <td>{% trans "Payed to you" %}, {{ currency_label }}</td>
                    <td>{% trans "Attracted visitors payments count" %}</td>
                    <td>{% trans "Attracted visitors payments amount" %}, {{ currency_label }}</td>
                    <td>{% trans "Reward per transaction" %}</td>
                </tr>
            </thead>
            <tr>
                <td>{{ affiliate.balance }}</td>
                <td>{{ affiliate.total_payed }}</td>
                <td>{{ affiliate.total_payments_count }}</td>
                <td>{{ affiliate.total_payments_amount }}</td>
                <td>{{ affiliate.get_printable_reward }}</td>
            </tr>
        </table>

        <h3>{% trans "Your visitors stats" %}</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>{% trans "Date" %}</td>
                    <td>{% trans "Page views" %}</td>
                    <td>{% trans "Unique visitors" %}</td>
                    <td>{% trans "Number of payments" %}</td>
                    <td>{% trans "Payments amount" %}, {{currency_label}}</td>
                    <td>{% trans "Reward amount" %}, {{currency_label}}</td>
                </tr>
            </thead>
            {% for vstat in visitor_stats %}
                <tr>
                    <td>{{ vstat.date }}</td>
                    <td>{{ vstat.total_views }}</td>
                    <td>{{ vstat.unique_visitors }}</td>
                    <td>{{ vstat.payments_count }}</td>
                    <td>{{ vstat.payments_amount }}</td>
                    <td>{{ vstat.rewards_amount }}</td>
                </tr>
            {% endfor %}
        </table>

        <h3>{% trans "Your withdraw transactions" %}</h3>
        {% if pay_requests %}
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>{% trans "ID" %}</td>
                        <td>{% trans "Amount" %}, {{ currency_label }}</td>
                        <td>{% trans "Status" %}</td>
                        <td>{% trans "Created at" %}</td>
                        <td>{% trans "Payed at" %}</td>
                    </tr>
                </thead>
                {% for pay_request in pay_requests %}
                    <tr class="{% if pay_request.is_done %}success{% else %}warning{% endif %}">
                        <td>{{ pay_request.pk }}</td>
                        <td>{{ pay_request.amount }}</td>
                        <td>{{ pay_request.get_status_display }}</td>
                        <td>{{ pay_request.created_at }}</td>
                        <td>{{ pay_request.payed_at }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <div>{% trans "There are no payment requests made yet" %}</div>
        {% endif %}
    {% else %}
        {% trans "Currently you don't have affiliate program. Please, enable it first." %}
    {% endif %}
{% endblock %}

{% block submit_button %}
    {% if affiliate %}
        {% if requested %}
            <button class="btn btn-warning" type="submit" disabled="disabled">
                {% trans "Payment request already sent (pending)" %}
            </button>
        {% elif avaliable_for_request %}
            <button class="btn btn-success" type="submit">
                {% trans "Request for payment" %}
            </button>
        {% else %}
            <div>{% blocktrans with amount=min_request_amount %}You need minimum {{ amount }} {{currency_label }} in your balance to make a payment request{% endblocktrans %}</div>
            <button class="btn btn-default" type="submit"  disabled="disabled">
                {% trans "Balance is too low for payment request" %}
            </button>
        {% endif %}
    {% else %}
        <button class="btn btn-success" type="submit">
            {% trans "Create affiliate" %} &raquo;
        </button>
    {% endif %}
{% endblock %}

templates/templates/partner/affiliate_base.html
{% extends "common/base.html" %}

{% load url from future %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load affiliate_tags %}

{% block title %}{% trans "Affiliate program" %}{% endblock title %}

{% block content %}
<h1>{% trans "Affiliate program" %}</h1>

<div class="affiliate-content">
    {% block affiliate_content %}
    {% endblock %}
</div>

<form class="signup" id="signup_form" method="post" action=".">
  {% csrf_token %}
  {{ form|crispy }}
  {% block submit_button %}{% endblock %}
</form>


{% endblock content %}